# Generated by Django 4.2.9 on 2026-06-13 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scholarships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('applied_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('applied_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('applied_ielts', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('scholarship_tier', models.IntegerField(default=0, help_text='Scholarship % awarded: 100, 75, 50, 25, or 0')),
                ('personal_statement', models.TextField(blank=True, help_text='Why do you want this scholarship?')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes on this application')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('student', 'scholarship')},
            },
        ),
    ]
