# Generated by Django 4.2.9 on 2026-06-16 18:43

import apps.applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='challan_amount',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='application',
            name='challan_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='challan_image',
            field=models.ImageField(blank=True, help_text='Signed/stamped challan receipt uploaded by student', null=True, upload_to=apps.applications.models.challan_upload_path),
        ),
        migrations.AddField(
            model_name='application',
            name='challan_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='challan_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='personal_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='scholarship_tier',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending — Challan Due'), ('challan_paid', 'Challan Uploaded — Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
