# Generated by Django 4.2.9 on 2026-06-13 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('university_name', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('USA', 'United States'), ('Canada', 'Canada'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Belgium', 'Belgium'), ('Denmark', 'Denmark'), ('Ireland', 'Ireland'), ('UK', 'United Kingdom'), ('Other', 'Other European')], max_length=50)),
                ('degree_level', models.CharField(choices=[('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD'), ('any', 'Any Level')], max_length=20)),
                ('required_cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum CGPA out of 4.0', max_digits=3, null=True)),
                ('required_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum percentage required', max_digits=5, null=True)),
                ('ielts_required', models.DecimalField(blank=True, decimal_places=1, help_text='Minimum IELTS score', max_digits=3, null=True)),
                ('scholarship_amount', models.CharField(help_text='e.g. Full Tuition, $10,000/year, 50% waiver', max_length=100)),
                ('application_deadline', models.DateField()),
                ('seats_available', models.IntegerField(default=0, help_text='0 means unlimited')),
                ('description', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('application_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='scholarships.scholarship')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_scholarships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('student', 'scholarship')},
            },
        ),
    ]
