# Generated by Django 4.2.9 on 2026-07-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='application_deadline',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='country',
            field=models.CharField(choices=[('USA', 'United States'), ('Canada', 'Canada'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Netherlands', 'Netherlands'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Finland', 'Finland'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Belgium', 'Belgium'), ('Denmark', 'Denmark'), ('Ireland', 'Ireland'), ('UK', 'United Kingdom'), ('Other', 'Other European')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='degree_level',
            field=models.CharField(choices=[('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD'), ('any', 'Any Level')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
